export const projects = [
  {
    id: 'leadmanager',
    title: 'LeadManager CRM',
    tagline: 'Enterprise CRM for Growing Businesses',
    description: 'Full stack CRM platform helping businesses track leads, manage sales pipelines, and convert prospects into customers. Built for consultants, agencies, and service businesses seeking powerful organization without enterprise complexity. The architecture demonstrates backend proficiency and system design thinking through a RESTful API with optimized data models.',
    image: '/projects/leadmanager.png',
    liveUrl: 'https://crm-dashboard-navy.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/leadmanager-crm',
    caseStudyUrl: 'https://crm-dashboard-navy.vercel.app',
    highlights: [
      'Demo CRM with pipeline tracking and lead management',
      'Real-time pipeline updates with optimistic UI for instant feedback',
      'API response times under 100ms with MongoDB indexing',
    ],
    tech: ['React', 'Tailwind', 'Node.js', 'Express', 'MongoDB'],
    technicalDepth: {
      challenge: 'Different businesses need different lead fields and sales processes. A rigid SQL schema would require migrations every time a client wanted custom fields, slowing iteration and reducing flexibility.',
      solution: 'Chose MongoDB for its flexible schema design, allowing each business to customize lead structures without database migrations. This enabled rapid prototyping and quick iteration based on user feedback.',
      architecture: 'Built a RESTful API with Express and Mongoose for schema validation. Implemented pipeline status tracking with optimistic updates on the frontend for instant user feedback. Used MongoDB indexes on frequently queried fields (status, createdAt) to keep API responses under 100ms.',
      learned: 'Balancing flexibility with data integrity. While schemaless databases offer speed, I learned to enforce critical validations at the application layer using Mongoose schemas to prevent data inconsistencies.',
    },
    featured: true,
    category: 'Backend & System Design',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'ai-sales-ops',
    title: 'AI Sales Operations Platform',
    tagline: 'Intelligent Lead Management System',
    description: 'Production SaaS platform automating lead management with CSV processing, intelligent deduplication, automated enrichment, and AI powered scoring. Transforms messy data into actionable sales pipelines that drive revenue. This project showcases full stack capabilities with complex data processing algorithms and performance optimization.',
    image: '/projects/ai-sales-ops.png',
    liveUrl: 'https://ai-sales-ops-copilot.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/ai-sales-ops-frontend',
    caseStudyUrl: 'https://ai-sales-ops-copilot.vercel.app',
    highlights: [
      'Processes over 5,000 leads in under 30 seconds',
      '95% deduplication accuracy with smart matching algorithms',
      'Automated scoring with intelligent action recommendations',
    ],
    tech: ['React', 'Vite', 'Express', 'MongoDB', 'Tailwind'],
    technicalDepth: {
      challenge: 'Sales teams often import leads from multiple sources, creating duplicates with variations (different email cases, extra whitespace, nickname variations). Simple exact matching misses these, while processing 5,000+ records needs to be fast.',
      solution: 'Implemented a multi-field fuzzy matching algorithm that compares email, name, and phone across records. Used Levenshtein distance for string similarity, combined with normalization (lowercase, trim whitespace) before comparison.',
      architecture: 'Built the deduplication engine with hash maps for O(n) time complexity instead of nested loops. Normalized data gets hashed as keys, with similar matches grouped for user review. Frontend uploads CSV files, backend streams and processes them in chunks to handle large datasets without memory issues.',
      learned: 'The tradeoff between accuracy and performance. Initially tried comparing every field exhaustively, which was too slow. Learned to prioritize high-confidence matches (email exact match) first, then fall back to fuzzy matching only when needed. This hybrid approach achieved 95% accuracy while keeping processing under 30 seconds.',
    },
    featured: true,
    category: 'Full Stack & Data Processing',
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    id: 'evently',
    title: 'Evently',
    tagline: 'Professional Event Planning Platform',
    description: 'Event planning application for weddings, parties, and special occasions. Features real-time timeline management, guest organization with RSVP tracking, budget monitoring, vendor coordination, task checklists, and notes. Built with a consistent design system for a clean, intuitive interface. This project demonstrates frontend development and component architecture.',
    image: '/projects/evently.png',
    liveUrl: 'https://daniel-planner.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/daniel-planner',
    caseStudyUrl: 'https://daniel-planner.vercel.app',
    highlights: [
      'Complete event planning suite with 6 integrated modules',
      'Real time budget tracking with category breakdowns',
      'Beautiful, intuitive interface with modern animations',
    ],
    tech: ['Next.js 16', 'TypeScript', 'Framer Motion', 'Tailwind CSS'],
    technicalDepth: {
      challenge: 'Event planning involves multiple complex workflows (guests, budget, vendors, tasks, timeline, notes) that need to feel cohesive, not like six separate apps duct-taped together. The interface needed to be clean and intuitive for wedding planning while remaining functional.',
      solution: 'Built a reusable component architecture where each module (Dashboard, Timeline, Guests, etc.) shares the same design language and interaction patterns. Created a unified color system (indigo and coral) with consistent spacing, typography, and animation timing.',
      architecture: 'Adopted a mobile-first responsive approach using Tailwind CSS breakpoints throughout. Every component was designed for small screens first, then enhanced for desktop. Used Framer Motion strategically for micro-interactions (hover states, transitions) that enhance usability without overwhelming users. TypeScript provided type safety across all components, catching bugs before runtime.',
      learned: 'The importance of design systems in larger applications. Early on, I was writing one-off styles for each feature, which led to inconsistency. I learned to establish a design system first (colors, spacing scale, animation timing) and build components that compose together naturally. This made the codebase more maintainable and the user experience more cohesive.',
    },
    featured: true,
    category: 'Frontend & UX Design',
    gradient: 'from-indigo-500 to-orange-400',
  },
];

export const profile = {
  name: 'Daniel Aryee',
  title: 'Full-Stack Developer',
  location: 'London, UK',
  timezone: 'GMT/BST',
  email: 'tnix9826@tutamail.com',
  github: 'https://github.com/Veneering3759',
  linkedin: 'https://www.linkedin.com/in/daniel-a-869619399/',
  availability: 'Open to remote opportunities',
  preferences: 'Remote-first • US/EU companies welcome • Flexible timezone',
};

export const skills = {
  frontend: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Vite'],
  backend: ['Node.js', 'Express', 'MongoDB', 'RESTful APIs', 'Mongoose'],
  tools: ['Git', 'GitHub', 'Vercel', 'Render', 'MongoDB Atlas'],
};
