export const projects = [
  {
    id: 'leadmanager',
    title: 'LeadManager CRM',
    tagline: 'Enterprise CRM for Growing Businesses',
    description: 'Full stack CRM platform helping businesses track leads, manage sales pipelines, and convert prospects into customers. Built for consultants, agencies, and service businesses seeking powerful organization without enterprise complexity.',
    image: '/projects/leadmanager.png',
    liveUrl: 'https://crm-dashboard-navy.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/leadmanager-crm',
    caseStudyUrl: 'https://crm-dashboard-navy.vercel.app',
    highlights: [
      '67% average conversion from leads to paying clients',
      'Real time pipeline tracking with instant updates',
      'API response times under 100ms',
    ],
    tech: ['React', 'Tailwind', 'Node.js', 'Express', 'MongoDB'],
    featured: true,
    category: 'Full Stack',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'ai-sales-ops',
    title: 'AI Sales Operations Platform',
    tagline: 'Intelligent Lead Management System',
    description: 'Production SaaS platform automating lead management with CSV processing, intelligent deduplication, automated enrichment, and AI powered scoring. Transforms messy data into actionable sales pipelines that drive revenue.',
    image: '/projects/ai-sales-ops.png',
    liveUrl: 'https://ai-sales-ops-copilot.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/ai-sales-ops-frontend',
    caseStudyUrl: 'https://ai-sales-ops-copilot.vercel.app',
    highlights: [
      'Processes over 5,000 leads in under 30 seconds',
      '95% deduplication accuracy with smart matching algorithms',
      'Automated scoring with intelligent action recommendations',
    ],
    tech: ['React', 'Vite', 'Express', 'MongoDB', 'Tailwind'],
    featured: true,
    category: 'Full Stack',
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    id: 'daniel-planner',
    title: 'Daniel Planner',
    tagline: 'Professional Event Planning Platform',
    description: 'Comprehensive event planning application for weddings, parties, and special occasions. Features real time timeline management, guest organization with RSVP tracking, budget monitoring, vendor coordination, task checklists, and notes. Built with a luxury design system for an elegant planning experience.',
    image: '/projects/daniel-planner.png',
    liveUrl: 'https://daniel-planner.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/daniel-planner',
    caseStudyUrl: 'https://daniel-planner.vercel.app',
    highlights: [
      'Complete event planning suite with 6 integrated modules',
      'Real time budget tracking with category breakdowns',
      'Beautiful, intuitive interface with luxury animations',
    ],
    tech: ['Next.js 16', 'TypeScript', 'Framer Motion', 'Tailwind CSS'],
    featured: true,
    category: 'Full Stack',
    gradient: 'from-luxury-gold to-luxury-navy-light',
  },
];

export const profile = {
  name: 'Daniel Aryee',
  title: 'Full-Stack Developer',
  location: 'London, UK',
  timezone: 'GMT/BST',
  email: 'tnix9826@tutamail.com',
  github: 'https://github.com/Veneering3759',
  linkedin: 'https://www.linkedin.com/in/daniel-a-869619399/',
  availability: 'Open to remote opportunities',
  preferences: 'Remote-first • US/EU companies welcome • Flexible timezone',
};

export const skills = {
  frontend: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Vite'],
  backend: ['Node.js', 'Express', 'MongoDB', 'RESTful APIs', 'Mongoose'],
  tools: ['Git', 'GitHub', 'Vercel', 'Render', 'MongoDB Atlas'],
};
