export const projects = [
  {
    id: 'revenue-intel',
    title: 'Revenue Intel',
    tagline: 'Revenue analytics + churn + funnel insights for Stripe SaaS (with AI support chat).',
    description: 'Revenue intelligence platform that surfaces churn signals, checkout drop off, and pricing inefficiencies from Stripe subscription data. Includes an AI support chat with route aware context, a demo dashboard preloaded with realistic SaaS data, and demo mode guards so the live version is safe to share publicly.',
    image: '/projects/revenue-intel.png',
    liveUrl: 'https://revenue-intel.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/revenue-intel',
    caseStudyUrl: '/case-study/revenue-intel',
    highlights: [
      'Demo dashboard preloaded with realistic SaaS subscription and MRR data',
      'Stripe paygate with subscription tiers, plan upgrades, and billing portal',
      'AI support chat powered by OpenAI GPT-4o with route aware context prompts',
      'Demo mode guards isolate test data from production — safe to share publicly',
    ],
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Stripe', 'OpenAI API', 'MongoDB'],
    technicalDepth: {
      challenge: 'SaaS founders need to understand churn signals, checkout drop off, and MRR trends, but Stripe\'s native dashboard isn\'t designed for pattern recognition across these dimensions simultaneously. Pulling this data required understanding Stripe\'s subscription lifecycle, event model, and webhook delivery guarantees.',
      solution: 'Built a focused analytics dashboard that ingests Stripe webhook events, caches derived metrics in MongoDB, and surfaces them through a protected Next.js dashboard. Server side API routes act as a secure proxy — the Stripe secret key never leaves the server.',
      architecture: 'Next.js App Router with server components for initial data loads. Stripe Node SDK used exclusively in API routes and server components. MongoDB stores webhook payloads and derived subscription metrics with TTL indexes on raw event logs. NextAuth.js session middleware protects all dashboard routes at the middleware layer.',
      learned: 'Stripe\'s webhook delivery is "at least once" — not "exactly once." Built idempotency into the event handler using event IDs as unique keys before writing to MongoDB. Also learned that caching Stripe data locally reduces latency and avoids rate limits, but adds synchronization complexity that needs to be accounted for upfront.',
    },
    featured: true,
    flagship: true,
    category: 'SaaS / Stripe Analytics Platform',
    gradient: 'from-violet-500 to-indigo-600',
  },
  {
    id: 'leadmanager',
    title: 'LeadManager CRM',
    tagline: 'Pipeline Tracking for Growing Businesses',
    description: 'Full stack CRM platform for tracking leads and managing sales pipelines. Built for consultants and service businesses that need organized pipeline management without enterprise overhead. Demonstrates RESTful API design, optimistic UI updates, and MongoDB data modeling.',
    image: '/projects/leadmanager.png',
    liveUrl: 'https://crm-dashboard-navy.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/leadmanager-crm',
    caseStudyUrl: 'https://crm-dashboard-navy.vercel.app',
    highlights: [
      'RESTful API with Express and Mongoose schema validation',
      'Pipeline status tracking with optimistic UI for immediate feedback',
      'MongoDB indexes on status and createdAt for under 100ms API responses',
    ],
    tech: ['React', 'Tailwind CSS', 'Node.js', 'Express', 'MongoDB'],
    technicalDepth: {
      challenge: 'Different businesses need different lead fields and sales processes. A rigid SQL schema would require migrations every time a client wanted custom fields, slowing iteration and reducing flexibility.',
      solution: 'Chose MongoDB for its flexible schema design, allowing each business to customize lead structures without database migrations. This enabled rapid prototyping and quick iteration based on user feedback.',
      architecture: 'Built a RESTful API with Express and Mongoose for schema validation. Implemented pipeline status tracking with optimistic updates on the frontend for instant user feedback. Used MongoDB indexes on frequently queried fields (status, createdAt) to keep API responses under 100ms.',
      learned: 'Balancing flexibility with data integrity. While schemaless databases offer speed, I learned to enforce critical validations at the application layer using Mongoose schemas to prevent data inconsistencies.',
    },
    featured: true,
    category: 'Backend & System Design',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'evently',
    title: 'Evently',
    tagline: 'Event Planning Platform',
    description: 'Event planning application covering weddings, parties, and corporate occasions. Features timeline management, guest RSVP tracking, budget monitoring, vendor coordination, and task checklists. Demonstrates component architecture and design system implementation across multiple integrated modules.',
    image: '/projects/evently.png',
    liveUrl: 'https://daniel-planner.vercel.app',
    githubUrl: 'https://github.com/Veneering3759/daniel-planner',
    caseStudyUrl: 'https://daniel-planner.vercel.app',
    highlights: [
      'Six integrated modules sharing a unified design system and interaction patterns',
      'Mobile first responsive layout with Tailwind CSS breakpoints throughout',
      'Framer Motion for micro interactions: hover states and view transitions',
    ],
    tech: ['Next.js', 'TypeScript', 'Framer Motion', 'Tailwind CSS'],
    technicalDepth: {
      challenge: 'Event planning involves multiple complex workflows (guests, budget, vendors, tasks, timeline, notes) that need to feel cohesive, not like six separate apps duct taped together. The interface needed to be clean and intuitive for wedding planning while remaining functional.',
      solution: 'Built a reusable component architecture where each module (Dashboard, Timeline, Guests, etc.) shares the same design language and interaction patterns. Created a unified color system (indigo and coral) with consistent spacing, typography, and animation timing.',
      architecture: 'Adopted a mobile first responsive approach using Tailwind CSS breakpoints throughout. Every component was designed for small screens first, then enhanced for desktop. Used Framer Motion strategically for micro interactions (hover states, transitions) that enhance usability without overwhelming users. TypeScript provided type safety across all components, catching bugs before runtime.',
      learned: 'The importance of design systems in larger applications. Early on, I was writing one off styles for each feature, which led to inconsistency. I learned to establish a design system first (colors, spacing scale, animation timing) and build components that compose together naturally. This made the codebase more maintainable and the user experience more cohesive.',
    },
    featured: true,
    category: 'Frontend & Component Architecture',
    gradient: 'from-indigo-500 to-orange-400',
  },
];

export const profile = {
  name: 'Daniel Aryee',
  title: 'Full Stack Developer',
  location: 'London, UK',
  timezone: 'GMT/BST',
  email: 'tnix9826@tutamail.com',
  github: 'https://github.com/Veneering3759',
  linkedin: 'https://www.linkedin.com/in/daniel-a-869619399/',
  availability: 'Open to remote opportunities',
  preferences: 'Remote first · US/EU companies welcome · Flexible timezone',
};

export const skills = {
  frontend: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
  backend: ['Node.js', 'Express', 'MongoDB', 'Stripe', 'NextAuth.js'],
  tools: ['Git', 'GitHub', 'Vercel', 'MongoDB Atlas', 'Render'],
};
